# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
media_folder: 'assets/uploads'

publish_mode: editorial_workflow

collections:  
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false    
    create: true
    files:
      - name: "Global Settings"
        label: "Site Settings"
        file: "_config.yml"
        description: "General Site Settings"
        fields:
          - label: "title"
            name: title
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }